feat(ci): add GitHub Actions
Pushes will now be verified to be compliant with the styling and linters
as configured through pre-commit, when run inside a MR this will
automatically be scoped to that specific MR only.

Further more on tag events release binaries will now be build for every
available target and uploaded as a release for download.

diff --git a/.tools/bin/pre-commit b/.tools/bin/pre-commit
--- a/.tools/bin/pre-commit
+++ b/.tools/bin/pre-commit
@@ -20,6 +20,16 @@ run_hooks() {
   pre-commit run || return 1
 }
 
+run_hooks_ci() {
+  local from_ref
+  local to_ref
+
+  from_ref="${PRE_COMMIT_FROM_REF}"
+  to_ref="${PRE_COMMIT_TO_REF}"
+
+  pre-commit run --from-ref "${from_ref}" --to-ref "${to_ref}"
+}
+
 entrypoint() {
   local arg
 
@@ -44,6 +54,13 @@ entrypoint() {
   "run")
     log INFO "running pre-commit hooks:"
     if ! run_hooks; then
+      log ERROR "one or more hooks failed"
+      return 1
+    fi
+    ;;
+  "run-ci")
+    log INFO "running pre-commit hooks for MR context:"
+    if ! run_hooks_ci; then
       log ERROR "one or more hooks failed"
       return 1
     fi
